# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-20 09:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0002_auto_20160120_1458'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snippet',
            old_name='linenos',
            new_name='BusNo',
        ),
        migrations.RenameField(
            model_name='snippet',
            old_name='code',
            new_name='BusRoute',
        ),
        migrations.RenameField(
            model_name='snippet',
            old_name='title',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='snippet',
            old_name='language',
            new_name='longitude',
        ),
    ]
