# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-20 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0003_auto_20160120_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='longitude',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
