# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-20 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0007_remove_snippet_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='BusNo',
            field=models.CharField(blank=True, default='KA', max_length=100),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='latitude',
            field=models.CharField(blank=True, default='32', max_length=100),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='longitude',
            field=models.CharField(blank=True, default='24', max_length=100),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='time',
            field=models.CharField(blank=True, default='12.20', max_length=100),
        ),
    ]
